# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PrograMM\Piton\Проекты\gfgrf lkz lbvs\Приложени.ui
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from ApplicationData import ApplicationData


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("ЕГЭ Русский язык №4")
        Form.resize(439, 340)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 441, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lbl_1 = QtWidgets.QLabel(self.tab)
        self.lbl_1.setGeometry(QtCore.QRect(20, 70, 21, 20))
        self.lbl_1.setObjectName("lbl_1")
        self.lbl_2 = QtWidgets.QLabel(self.tab)
        self.lbl_2.setGeometry(QtCore.QRect(20, 90, 21, 20))
        self.lbl_2.setObjectName("lbl_2")
        self.lbl_3 = QtWidgets.QLabel(self.tab)
        self.lbl_3.setGeometry(QtCore.QRect(20, 110, 21, 20))
        self.lbl_3.setObjectName("lbl_3")
        self.lbl_4 = QtWidgets.QLabel(self.tab)
        self.lbl_4.setGeometry(QtCore.QRect(20, 130, 21, 20))
        self.lbl_4.setObjectName("lbl_4")
        self.label_ans = QtWidgets.QLabel(self.tab)
        self.label_ans.setGeometry(QtCore.QRect(90, 270, 161, 61))
        self.label_ans.setText("")
        self.label_ans.setObjectName("label_ans")
        self.lbl_5 = QtWidgets.QLabel(self.tab)
        self.lbl_5.setGeometry(QtCore.QRect(20, 150, 21, 20))
        self.lbl_5.setObjectName("lbl_5")
        self.btn_cont = QtWidgets.QPushButton(self.tab)
        self.btn_cont.setGeometry(QtCore.QRect(10, 280, 75, 21))
        self.btn_cont.setObjectName("btn_cont")
        self.lbl1 = QtWidgets.QLabel(self.tab)
        self.lbl1.setGeometry(QtCore.QRect(40, 70, 91, 20))
        self.lbl1.setObjectName("lbl1")
        self.lbl2 = QtWidgets.QLabel(self.tab)
        self.lbl2.setGeometry(QtCore.QRect(40, 90, 91, 20))
        self.lbl2.setObjectName("lbl2")
        self.lbl3 = QtWidgets.QLabel(self.tab)
        self.lbl3.setGeometry(QtCore.QRect(40, 110, 91, 20))
        self.lbl3.setObjectName("lbl3")
        self.lbl4 = QtWidgets.QLabel(self.tab)
        self.lbl4.setGeometry(QtCore.QRect(40, 130, 91, 20))
        self.lbl4.setObjectName("lbl4")
        self.lbl5 = QtWidgets.QLabel(self.tab)
        self.lbl5.setGeometry(QtCore.QRect(40, 150, 91, 20))
        self.lbl5.setObjectName("lbl5")
        self.acw = QtWidgets.QLineEdit(self.tab)
        self.acw.setGeometry(QtCore.QRect(250, 280, 113, 20))
        self.acw.setObjectName("acw")
        self.Vvod = QtWidgets.QLabel(self.tab)
        self.Vvod.setGeometry(QtCore.QRect(250, 240, 151, 31))
        self.Vvod.setObjectName("Vvod")
        self.info = QtWidgets.QLabel(self.tab)
        self.info.setGeometry(QtCore.QRect(10, 10, 301, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.info.setFont(font)
        self.info.setMouseTracking(False)
        self.info.setTabletTracking(False)
        self.info.setAcceptDrops(False)
        self.info.setAutoFillBackground(False)
        self.info.setWordWrap(True)
        self.info.setObjectName("info")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(370, 280, 61, 20))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.Information = QtWidgets.QWidget()
        self.Information.setObjectName("Information")
        self.textBrowser = QtWidgets.QTextBrowser(self.Information)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 441, 321))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.Information, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.fullen()
        self.cont()
        self.kn()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_1.setText(_translate("Form", "1)"))
        self.lbl_2.setText(_translate("Form", "2)"))
        self.lbl_3.setText(_translate("Form", "3)"))
        self.lbl_4.setText(_translate("Form", "4)"))
        self.lbl_5.setText(_translate("Form", "5)"))
        self.btn_cont.setText(_translate("Form", "Продолжить"))
        self.lbl1.setText(_translate("Form", "TextLabel"))
        self.lbl2.setText(_translate("Form", "TextLabel"))
        self.lbl3.setText(_translate("Form", "TextLabel"))
        self.lbl4.setText(_translate("Form", "TextLabel"))
        self.lbl5.setText(_translate("Form", "TextLabel"))
        self.Vvod.setText(_translate("Form", "Введите ответ:"))
        self.info.setText(_translate("Form", "В ответе укажите вариант, в котором НЕВЕРНО выделена буква, обозначающая ударный гласный звук"))
        self.pushButton.setText(_translate("Form", "Ответить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Практика"))
        self.Information.setToolTip(_translate("Form", "<html><head/><body><p>Информация</p><p><br/></p></body></html>"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Для выполнения задания 4 ЕГЭ по русскому языку рекомендуется следующий алгоритм:</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:8pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Внимательно прочитайте все слова.</li>\n"
"<li style=\" font-size:8pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Среди предложенных в тесте слов выберите те, которые можно объяснить правилом, вспомните правила орфоэпии. Самые маленькие группы слов: прилагательные, деепричастия, наречия.</li>\n"
"<li style=\" font-size:8pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Если после этого все еще остались варианты, то вспомните слова, которые не подчиняются правилам или являются исключениями (такие слова как «клАла», «послАла», «откУпорить» и другие).</li></ol>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Для того, чтобы запомнить ударения, рекомендуется выучить правила. Слова нужно учить не вперемешку, а группами, объединенными общим звучанием.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Information), _translate("Form", "Информация"))
    def fullen(self):
        self.pere = ApplicationData.task_and_response()
        pere_keys = self.pere[0]
        self.lbl1.setText(pere_keys[0])
        self.lbl2.setText(pere_keys[1])
        self.lbl3.setText(pere_keys[2])
        self.lbl4.setText(pere_keys[3])
        self.lbl5.setText(pere_keys[4])
        self.label_ans.setText("")


    def kn(self):
        self.pushButton.clicked.connect(self.ans)
    def cont(self):
        self.btn_cont.clicked.connect(self.fullen)

    def ans(self):
        if str(self.acw.text()) != str(self.pere[1]):
            self.label_ans.setText("Неверно(")
        else:
            self.label_ans.setText("Правильно!!!")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())